import type { Express, Request, Response } from "express";
import {
  streamConceptNoteChat,
  handleUserEdit,
  getConceptNoteState,
  setConceptNoteState,
} from "../services/conceptNoteAgent";
import {
  createEmptyConceptNote,
  CONCEPT_NOTE_SECTIONS,
  type ConceptNoteState,
} from "@shared/concept-note-schema";

export function registerConceptNoteRoutes(app: Express): void {
  // Create a new concept note session
  app.post("/api/concept-note", async (req: Request, res: Response) => {
    const { city, projectId } = req.body;
    if (!city) {
      return res.status(400).json({ error: "city is required" });
    }

    const state = createEmptyConceptNote(projectId || "sample-project", city);
    setConceptNoteState(state.id, state);

    res.json({ noteId: state.id, state });
  });

  // Get current concept note state
  app.get("/api/concept-note/:noteId", async (req: Request, res: Response) => {
    const state = getConceptNoteState(req.params.noteId);
    if (!state) {
      return res.status(404).json({ error: "Note not found" });
    }
    res.json(state);
  });

  // Chat with the agent (SSE stream)
  app.post("/api/concept-note/:noteId/chat", async (req: Request, res: Response) => {
    const { message } = req.body;
    if (!message) {
      return res.status(400).json({ error: "message is required" });
    }

    const state = getConceptNoteState(req.params.noteId);
    if (!state) {
      return res.status(404).json({ error: "Note not found" });
    }

    await streamConceptNoteChat(req.params.noteId, message, res, state);
  });

  // User edits a field from the document panel (triggers cascade via SSE)
  app.post("/api/concept-note/:noteId/edit", async (req: Request, res: Response) => {
    const { sectionId, field, value } = req.body;
    if (!sectionId || !field || value === undefined) {
      return res.status(400).json({ error: "sectionId, field, and value are required" });
    }

    await handleUserEdit(req.params.noteId, sectionId, field, value, res);
  });

  // Export concept note as markdown
  app.get("/api/concept-note/:noteId/export", async (req: Request, res: Response) => {
    const state = getConceptNoteState(req.params.noteId);
    if (!state) {
      return res.status(404).json({ error: "Note not found" });
    }

    const markdown = exportToMarkdown(state);
    res.setHeader("Content-Type", "text/markdown");
    res.setHeader("Content-Disposition", `attachment; filename="concept-note-${state.city}.md"`);
    res.send(markdown);
  });

  // Get section registry (for building the UI)
  app.get("/api/concept-note/sections", async (_req: Request, res: Response) => {
    res.json(CONCEPT_NOTE_SECTIONS);
  });
}

function exportToMarkdown(state: ConceptNoteState): string {
  const lines: string[] = [];
  lines.push(`# ${state.metadata.projectName || 'Concept Note'} — Nota Conceitual`);
  lines.push('');
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push(`> City: ${state.city}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const sec of CONCEPT_NOTE_SECTIONS) {
    const section = state.sections[sec.id];
    lines.push(`## ${sec.title}`);
    lines.push('');

    if (Object.keys(section.fields).length === 0) {
      lines.push('*(Not yet filled)*');
    } else {
      for (const [fieldName, field] of Object.entries(section.fields)) {
        if (field.value) {
          lines.push(`### ${fieldName.replace(/_/g, ' ')}`);
          lines.push('');
          lines.push(String(field.value));
          if (field.source) {
            lines.push('');
            lines.push(`> Source: ${field.source} (${field.confidence} confidence)`);
          }
          lines.push('');
        }
      }
    }

    // Show gaps for this section
    const sectionGaps = state.gaps.filter(g => g.sectionId === sec.id);
    if (sectionGaps.length > 0) {
      lines.push('**Gaps:**');
      for (const gap of sectionGaps) {
        lines.push(`- ⚠️ ${gap.field}: ${gap.reason} (${gap.severity})`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Metadata
  lines.push('## Metadata');
  lines.push('');
  lines.push(`- **Gaps identified**: ${state.gaps.length}`);
  lines.push(`- **Edits logged**: ${state.editLog.length}`);
  lines.push(`- **Current phase**: ${state.phase}/10`);
  lines.push(`- **Generated by**: NBS Concept Note Module (Claude Agent SDK)`);

  return lines.join('\n');
}
