// ============================================================================
// THE BAIRRO RISK TABLE — 94 rows, generated, so any layer can check a record
// ============================================================================
// `porto-alegre-neighborhood-zones.json` is 2.5 MB of geometry and lives in
// client/public for the map. The five numbers per bairro that the CBO flow
// actually stores — the three within-city hazard percentiles, the population
// and the poverty rate — are about 5 kB, and pulling them out means the server,
// the doctor and a backfill can all check a stored record against the truth
// without loading a map file.
//
//   npx tsx scripts/generate-bairro-risk-table.ts
// ============================================================================
import * as fs from 'fs';
import * as path from 'path';

const SRC = 'client/public/sample-data/porto-alegre-neighborhood-zones.json';
const OUT = 'shared/bairro-risk-table.ts';

const pct = (rank: unknown) => Math.round(Math.max(0, Math.min(1, Number(rank) || 0)) * 100);

const data = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const rows = (data.geoJson?.features ?? [])
  .map((f: any) => f.properties)
  .filter((p: any) => p?.neighbourhoodName)
  .map((p: any) => ({
    name: String(p.neighbourhoodName),
    flood: pct(p.floodRank),
    heat: pct(p.heatRank),
    landslide: pct(p.landslideRank),
    population: Math.round(Number(p.populationTotal) || 0),
    povertyPct: Number(((Number(p.povertyRate) || 0) * 100).toFixed(1)),
  }))
  .sort((a: any, b: any) => a.name.localeCompare(b.name, 'pt-BR'));

const body = rows
  .map((r: any) => `  { name: ${JSON.stringify(r.name)}, flood: ${r.flood}, heat: ${r.heat}, landslide: ${r.landslide}, population: ${r.population}, povertyPct: ${r.povertyPct} },`)
  .join('\n');

fs.writeFileSync(
  path.resolve(OUT),
  `// ⚠️ GENERATED by scripts/generate-bairro-risk-table.ts — do not edit by hand.
// Source: ${SRC} (${data.generatedAt ?? 'undated'}).
//
// The five numbers the CBO flow stores per bairro, lifted out of a 2.5 MB map
// file so the server, the cohort doctor and the backfill can all check a stored
// record against the truth. Percentiles are WITHIN-CITY RANKS (floodRank × 100),
// which is the basis shared/risk-display.ts documents and the Site Explorer
// uses — never the compressed absolute means.

export interface BairroRisk {
  name: string;
  /** Within-city percentile, 0–100. */
  flood: number;
  heat: number;
  landslide: number;
  population: number;
  povertyPct: number;
}

export const BAIRRO_RISK: BairroRisk[] = [
${body}
];
`,
);
console.log(`${rows.length} bairros → ${OUT}`);
