// ============================================================================
// THE PRINTED HOJA DE RUTA — the copy that goes into a room
// ============================================================================
// A markdown download is a file. This is a document: it opens in the phone's
// browser, and Share → Print → Save as PDF turns it into something you can hand
// round a table, attach to an e-mail, or read aloud in an assembly.
//
// That last use is the one that shaped it. The organisation will defend this in
// front of neighbours who did not sit through the workshop, so:
//
//   · the word RASCUNHO is the first thing on the page, at the top of every
//     printed sheet, because a draft mistaken for a decision is the failure
//     mode that costs the most here;
//   · "essa faixa não é dinheiro que alguém já tem" sits in the same weight of
//     type as the figure it qualifies, never as a footnote;
//   · every block keeps its ← (where it came from) and ↻ (what would change
//     it), because being able to say "this line came from the ficha, not from
//     us" is what makes it arguable rather than official;
//   · it prints in black on white with no background fills, because it will be
//     printed on whatever is in the office.
//
// Self-contained: no external CSS, no fonts, no scripts. It has to render on a
// six-year-old Android with no data left in the month.
// ============================================================================

import type { Roadmap } from '@shared/w3-roadmap';

const esc = (s: unknown): string =>
  String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

/**
 * The chat copy uses **bold** and _italics_; the page should too rather than
 * printing the delimiters.
 *
 * ⚠️ The italic half was missing, so the scale statement's own caveat — the one
 * sentence saying the reference volumes are for comparing scales and not for
 * sizing the works — printed as "_Ordem de grandeza: … não pra dimensionar a
 * obra._" on a page an organisation takes to a meeting. Underscores are matched
 * only at word boundaries, so nothing that merely contains one is touched.
 */
const md = (s: unknown): string =>
  esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[\s(])_([^_\n]{1,400}?)_(?=[\s.,;:)!?]|$)/g, '$1<em>$2</em>')
    .replace(/\n/g, '<br>');

const STATE_LABEL: Record<string, { pt: string; en: string }> = {
  ready: { pt: 'Pronto pra orçar', en: 'Ready to quote' },
  needs_study: { pt: 'Precisa de um estudo técnico', en: 'Needs a technical study' },
  needs_permission: { pt: 'Precisa de autorização', en: 'Needs permission' },
  needs_site: { pt: 'Falta marcar o lugar', en: 'No place marked yet' },
};

const T = {
  pt: {
    draft: 'RASCUNHO — para validar e ajustar',
    p1: 'O projeto', p2: 'O que ele pede', road: 'O caminho daqui', open: 'O que ficou em aberto',
    openWhy: 'Isso não é falha de vocês. É o próximo trecho do caminho — e boa parte dele é da coordenação.',
    org: 'vocês', coord: 'coordenação', openTag: 'em aberto',
    foot: 'Documento gerado pelo Encontro 3 a partir do que a organização contou. Nada aqui está fechado: cada bloco diz de onde veio e o que muda ele.',
    printed: 'Gerado em',
  },
  en: {
    draft: 'DRAFT — to validate and adjust',
    p1: 'The project', p2: 'What it asks for', road: 'The road from here', open: 'What is still open',
    openWhy: 'This is not a failing on your side. It is the next stretch of the road — and much of it belongs to the coordination.',
    org: 'you', coord: 'coordination', openTag: 'open',
    foot: 'Generated by Encontro 3 from what the organisation told us. Nothing here is settled: every block says where it came from and what would change it.',
    printed: 'Generated on',
  },
};

function block(b: { title: string; lines: string[]; from?: string; changedBy?: string; open?: boolean }, t: typeof T.pt): string {
  return `
    <section class="blk">
      <h3>${esc(b.title)}${b.open ? `<span class="tag">${esc(t.openTag)}</span>` : ''}</h3>
      ${b.lines.map(l => `<p>${md(l)}</p>`).join('')}
      ${b.from ? `<p class="from">← ${esc(b.from)}</p>` : ''}
      ${b.changedBy ? `<p class="chg">↻ ${esc(b.changedBy)}</p>` : ''}
    </section>`;
}

export function renderRoadmapHtml(roadmap: Roadmap, lang: 'pt' | 'en' = 'pt'): string {
  const t = T[lang];
  const state = STATE_LABEL[roadmap.state]?.[lang] ?? roadmap.state;
  const title = `${roadmap.solutions.join(' + ') || '—'} · ${roadmap.siteName || roadmap.bairro}`;
  const today = new Date().toLocaleDateString(lang === 'pt' ? 'pt-BR' : 'en-GB');

  return `<!doctype html>
<html lang="${lang === 'pt' ? 'pt-BR' : 'en'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
  @page { size: A4; margin: 16mm 14mm; }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    color: #16201a; background: #fff; margin: 0;
    font-size: 15px; line-height: 1.55;
    -webkit-text-size-adjust: 100%;
  }
  .sheet { max-width: 760px; margin: 0 auto; padding: 26px 20px 60px; }
  .draft {
    font-size: 11px; font-weight: 800; letter-spacing: .1em;
    color: #7a5a12; background: #fdf4e0; border: 1px solid #e8d5a6;
    border-radius: 4px; padding: 5px 10px; display: inline-block; margin-bottom: 12px;
  }
  h1 { font-size: 22px; line-height: 1.2; margin: 0 0 4px; letter-spacing: -.01em; }
  .sub { color: #5c665f; font-size: 14px; margin: 0 0 10px; }
  .verdict {
    display: inline-block; font-size: 12px; font-weight: 700;
    border: 1px solid #9fb3a6; border-radius: 20px; padding: 3px 11px; color: #24493a;
  }
  h2 {
    font-size: 11px; letter-spacing: .1em; text-transform: uppercase; color: #6d776f;
    border-bottom: 1px solid #d9e0da; padding-bottom: 5px; margin: 30px 0 12px;
  }
  .blk { margin-bottom: 15px; break-inside: avoid; page-break-inside: avoid; }
  .blk h3 { font-size: 12px; letter-spacing: .04em; text-transform: uppercase; color: #4c574f; margin: 0 0 4px; }
  .blk .tag {
    font-size: 9.5px; font-weight: 700; letter-spacing: .04em; text-transform: none;
    border: 1px solid #e0c98d; color: #7a5a12; border-radius: 20px; padding: 1px 7px; margin-left: 7px;
  }
  .blk p { margin: 0 0 4px; }
  .blk .from { font-size: 11.5px; font-style: italic; color: #8a938c; }
  .blk .chg { font-size: 11.5px; color: #5c665f; }
  ol { list-style: none; padding: 0; margin: 0; }
  ol li {
    display: flex; gap: 11px; padding: 8px 0; border-bottom: 1px solid #ecefec;
    break-inside: avoid; page-break-inside: avoid;
  }
  ol li .n { font-variant-numeric: tabular-nums; color: #8a938c; font-size: 13px; min-width: 20px; }
  ol li .who { display: block; font-size: 11.5px; color: #5c665f; margin-top: 2px; }
  .openbox { border: 1px solid #e8d5a6; background: #fdf9f0; border-radius: 6px; padding: 12px 14px; margin-top: 12px; }
  .openbox p { margin: 0 0 5px; font-size: 14px; }
  .openbox .why { font-size: 12px; font-style: italic; color: #5c665f; margin: 0; }
  footer { margin-top: 34px; border-top: 1px solid #d9e0da; padding-top: 12px; font-size: 11.5px; color: #8a938c; }
  .noprint { margin: 0 0 18px; }
  .noprint button {
    font: inherit; font-size: 14px; font-weight: 600; padding: 9px 16px;
    border: 1px solid #2c6b4b; background: #2c6b4b; color: #fff; border-radius: 7px; cursor: pointer;
  }
  /* Printed: drop the control, keep the draft warning on every sheet, and make
     sure nothing depends on a background colour surviving the printer. */
  @media print {
    .noprint { display: none !important; }
    .sheet { padding: 0; max-width: none; }
    .draft { border-color: #000; color: #000; background: transparent; }
    .openbox { border-color: #999; background: transparent; }
    a { color: inherit; text-decoration: none; }
  }
</style>
</head>
<body>
<div class="sheet">
  <div class="noprint">
    <button onclick="window.print()">${lang === 'pt' ? 'Imprimir ou salvar em PDF' : 'Print or save as PDF'}</button>
  </div>

  <div class="draft">${esc(t.draft)}</div>
  <h1>${esc(roadmap.solutions.join(' + ') || '—')}</h1>
  <p class="sub">${esc([roadmap.siteName, roadmap.bairro].filter(Boolean).join(' · '))}${roadmap.orgName ? ` — ${esc(roadmap.orgName)}` : ''}</p>
  <span class="verdict">${esc(state)}</span>

  <h2>${esc(t.p1)}</h2>
  ${roadmap.what.map(b => block(b, t)).join('')}

  <h2>${esc(t.p2)}</h2>
  ${roadmap.how.map(b => block(b, t)).join('')}

  ${roadmap.steps.length ? `
  <h2>${esc(t.road)}</h2>
  <ol>
    ${roadmap.steps.map(s => `
      <li>
        <span class="n">${s.n}.</span>
        <span>
          ${esc(s.title)}
          <span class="who">→ ${esc(s.owner === 'org' ? (s.ownerName ?? t.org) : t.coord)}${s.blockedBy ? ` · ${esc(s.blockedBy)}` : ''}</span>
        </span>
      </li>`).join('')}
  </ol>` : ''}

  ${roadmap.open.length ? `
  <h2>${esc(t.open)}</h2>
  <div class="openbox">
    ${roadmap.open.map(g => `<p>• ${esc(g)}</p>`).join('')}
    <p class="why">${esc(t.openWhy)}</p>
  </div>` : ''}

  <footer>
    <p>${esc(t.foot)}</p>
    <p>${esc(t.printed)} ${esc(today)}.</p>
  </footer>
</div>
</body>
</html>`;
}
